
server:
  name: "Valheim"
  motd: "Valheim+ Server"
  password: "12345"
  adminlist: |
    # one line per steam id
  whitelist: |
    # one line per steam id
  blacklist: |
    # one line per steam id

map:
  name: "Dedicated"
  # Update this to your specific environment and storage class
  storageClass: standard
  storageSize: 1G

logs:
  # Update this to your specific environment and storage class
  storageClass: standard
  storageSize: 1G

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

image:
  name: adaliszk/valheim-server
  tag: 0.146.8
  pullPolicy: IfNotPresent
  pullSecrets: []

service:
  enabled: true
  type: LoadBalancer

  ports:
    valheim:
      port: 2456
      targetPort: 2456
      protocol: UDP
    msqp:
      port: 2457
      targetPort: 2457
      protocol: UDP
    msqp-default:
      port: 27015
      targetPort: 2457
      protocol: UDP

  # Additional annotations (e.g. for cloud provider specific config)
  annotations: {}

  # Additional service labels (e.g. for filtering Service by custom labels)
  labels: {}

  # Additional entries here will be added to the service spec. Cannot contains
  # type, selector or ports entries.
  spec: {}
    # externalTrafficPolicy: Cluster
    # loadBalancerIP: "1.2.3.4"
  # clusterIP: "2.3.4.5"

# Valheim Plus configuration (if you use the :plus* tags)
# for further information please refer to: https://github.com/valheimPlus/ValheimPlus#features
plus:
  enabled: false

  # Enable the various features you'd like with "enabled" and customize each of them by changing the default value
  # When a KeyCode is expected, refer to: https://docs.unity3d.com/ScriptReference/KeyCode.html

  server:
    enabled: false
    maxPlayers: 10
    disableServerPassword: false
    enforceMod: true
    dataRate: 60
    autoSaveInterval: 1200

  game:
    enabled: false
    gameDifficultyDamageScale: 0.4
    gameDifficultyHealthScale: 0.4
    extraPlayerCountNearby: 0
    setFixedPlayerCountTo: 0
    difficultyScaleRange: 200

  player:
    enabled: false
    baseMaximumWeight: 300
    baseMegingjordBuff: 150
    baseAutoPickUpRange: 2
    disableCameraShake: false
    baseUnarmedDamage: 10

  stamina:
    enabled: false
    dodgeStaminaUsage: 10
    encumberedStaminaDrain: 10
    jumpStaminaDrain: 10
    runStaminaDrain: 10
    sneakStaminaDrain: 10
    staminaRegen: 5
    staminaRegenDelay: 1
    swimStaminaDrain: 5

  staminaUsage:
    enabled: false
    axes: 0
    bows: 0
    clubs: 0
    knives: 0
    pickaxes: 0
    polearms: 0
    spears: 0
    swords: 0
    unarmed: 0
    hammer: 0
    hoe: 0

  experience:
    enabled: false
    swords: 0
    knives: 0
    clubs: 0
    polearms: 0
    spears: 0
    blocking: 0
    axes: 0
    bows: 0
    fireMagic: 0
    frostMagic: 0
    unarmed: 0
    pickaxes: 0
    woodCutting: 0
    jump: 0
    sneak: 0
    run: 0
    swim: 0

  hotkeys:
    enabled: false
    rollForwards: "F9"
    rollBackwards: "F10"

  hud:
    enabled: false
    showRequiredItems: false
    experienceGainedNotifications: false

  camera:
    enabled: false
    cameraMaximumZoomDistance: 6
    cameraBoatMaximumZoomDistance: 6
    cameraFOV: 65

  map:
    enabled: false
    shareMapProgression: false
    exploreRadius: 100
    playerPositionPublicOnJoin: false
    preventPlayerFromTurningOffPublicPosition: false
    removeDeathPinOnTombstoneEmpty: false

  time:
    enabled: false
    totalDayTimeInSeconds: 1200
    nightTimeSpeedMultiplier: 0

  advancedBuilding:
    enabled: false
    enterAdvancedBuildingMode: "F3"
    exitAdvancedBuildingMode: "F4"

  advancedEditing:
    enabled: false
    enterAdvancedEditingMode: "Keypad0"
    resetAdvancedEditingMode: "F7"
    abortAndExitAdvancedEditingMode: "F8"
    confirmPlacementOfAdvancedEditingMode: "KeypadEnter"

  beehive:
    enabled: false
    honeyProductionSpeed: 1200
    maximumHoneyPerBeehive: 4

  building:
    enabled: false
    noInvalidPlacementRestriction: false
    noWeatherDamage: false
    maximumPlacementDistance: 5

  structuralIntegrity:
    enabled: false
    disableStructuralIntegrity: false
    wood: 0
    stone: 0
    iron: 0
    hardwood: 0

  items:
    enabled: false
    noTeleportPrevention: false
    baseItemWeightReduction: 0
    itemStackMultiplier: 0

  fermenter:
    enabled: false
    fermenterDuration: 2400
    fermenterItemsProduced: 6

  fireplace:
    enabled: false
    onlyTorches: false

  food:
    enabled: false
    foodDurationMultiplier: 0

  workbench:
    enabled: false
    workbenchRange: 20
    disableRoofCheck: false

  furnace:
    enabled: false
    maximumOre: 10
    maximumCoal: 20
    coalUsedPerProduct: 2
    productionSpeed: 30

  kiln:
    enabled: false
    maximumWood: 20
    productionSpeed: 30

  ward:
    enabled: false
    wardRange: 20

  wagon:
    enabled: false
    wagonBaseMass: 20
    wagonExtraMassFromItems: 0