global:
  storageClass: ""
  imagePullSecrets: []
  imagePullPolicy: Always
  commonLabels: {}
  commonAnnotations: {}

persistence:
  storageClass: ""
  size: 12Gi

commonLabels: {}
labels: {}

commonAnnotations: {}
annotations: {}

image:
  registry: docker.io
  repository: adaliszk
  name: valheim-server
  tag: develop

server:
  timezone: Etc/UTC
  name: "Secure Valheim-Server by AdaLiszk"
  world: "dedicated"
  seed: ""
  password: "p4ssw0rd"
  crossplay: false
  public: true
  admins: []
  permitted: []
  banned: []

backups:
  retention: 4
  interval: 7200

service:
  type: LoadBalancer
  annotations: {}
  valheimPort: 2456
  steamPort: 2457