
# SERVER CONFIGURATION
# =============================================================================
server:
  name: "Valheim"
  motd: "Valheim on Kubernetes!"
  world: "Dedicated"
  password: "p4ssw0rd"
  public: "1"

  admins: [ ]
  permitted: [ ]
  banned: [ ]

  labels: { }
  annotations: { }
  resources: { }
  affinity: { }

  persistentData:
    storageClass: default
    storageSize: 3G

  persistentBackups:
    storageClass: default
    storageSize: 6G
    retention: 6

  persistentLogs:
    storageClass: default
    storageSize: 3G

  image:
    name: adaliszk/valheim-server
    tag: 0.150.3
    pullPolicy: IfNotPresent
    pullSecrets: [ ]

  ports:
    valheim:
      port: 2456
      targetPort: 2456
      protocol: UDP
    msqp:
      port: 2457
      targetPort: 2457
      protocol: UDP


# PORT FORWARD CONFIGURATION
# =============================================================================
ingress:
  enabled: false
  type: LoadBalancer

  ports:
    valheim:
      port: 2456
      targetPort: 2456
      protocol: UDP

    msqp:
      port: 2457
      targetPort: 2457
      protocol: UDP

    msqp-default:
      port: 27015
      targetPort: 2457
      protocol: UDP

  labels: { }
  annotations: { }
  spec: { }


# METRICS EXPORTER
# =============================================================================
metrics:
  enabled: false

  labels: { }
  annotations:
    prometheus.io/scrape: true
  resources: { }
  affinity: { }

  server:
    enabled: true

    service:
      enabled: true
      type: ClusterIP
      ports:
        http:
          port: 3903
          targetPort: 3903
          protocol: TCP

    image:
      name: adaliszk/valheim-server-monitoring
      tag: metrics-0.150.3
      pullPolicy: IfNotPresent
      pullSecrets: [ ]

  node:
    enabled: true

    service:
      enabled: true
      type: ClusterIP
      ports:


    image:
      name: ""
      tag: ""
      pullPolicy: IfNotPresent
      pullSecrets: [ ]


# METRICS DASHBOARD
# =============================================================================
dashboard:
  enabled: false

  labels: { }
  annotations: { }
  resources: { }
  affinity: { }

  adminPassword: p4ssw0rd

  service:
    enabled: true
    type: ClusterIP
    ports:
      http:
        port: 3000
        targetPort: 3000
        protocol: TCP

