# =============================================================================
server:
  name: "Valheim Server"
  password: "12345"
  adminlist: []
  permitted: []
  banned: []

# =============================================================================
world:
  name: "Dedicated"
  # Update this to your specific environment and storage class
  # We recommend SSD storage!
  storageClass: standard
  storageSize: 2G

# =============================================================================
backups:
  # Update this to your specific environment and storage class
  storageClass: standard
  storageSize: 6G

  # how many world saves should it keep?
  saves:
    name: "auto"
    retention: 6

  # how many saves should be kept before a connection was made
  connections:
    name: "connect"
    retention: 1

# =============================================================================
logs:
  # Update this to your specific environment and storage class
  # We recommend SSD storage!
  storageClass: standard
  storageSize: 2G

# =============================================================================
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# =============================================================================
image:
  name: adaliszk/valheim-server
  tag: 0.146.8
  pullPolicy: IfNotPresent
  pullSecrets: []

# =============================================================================
service:
  enabled: true
  type: LoadBalancer
  ports:

    valheim:
      port: 2456
      targetPort: 2456

    msqp:
      port: 2457
      targetPort: 2457

    msqp-default:
      port: 27015
      targetPort: 2457

  # Additional annotations (e.g. for cloud provider specific config)
  annotations: {}

  # Additional service labels (e.g. for filtering Service by custom labels)
  labels: {}

  # Additional entries here will be added to the service spec. Cannot contains
  # type, selector or ports entries.
  # clusterIP: "2.3.4.5"
  spec: {}
    # externalTrafficPolicy: Cluster
  # loadBalancerIP: "1.2.3.4"

# =============================================================================
landing-page:
  enabled: true
  title: "My Valheim Server"
  description: >
    Welcome to my Valheim Server, we are in Kubernetes now!
  resources: { }
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# =============================================================================
prometheus:
  enabled: true
  persistance:
    storageClass: standard
    storageSize: 2G
  resources: { }
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# =============================================================================
grafana:
  enabled: true
  persistance:
    storageClass: standard
    stroageSize: 2G
  resources: { }
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# =============================================================================
ingress:
  enabled: true
  type: Ingress

  host: "yourdomain.com"
  https:
    enabled: true

  annotations: {}

  rules:

    landing-page:
      enabled: true
      service:
        name: landing-page
        port: 8080
      pathType: Prefix
      path: /

    metrics-page:
      enabled: false
      service:
        name: prometheus
        port: 8080
      pathType: Prefix
      path: /prometheus

    dashboard-page:
      enabled: true
      service:
        name: grafana
        port: 8080
      pathType: Prefix
      path: /metrics
