# ==============================================================================
version: "3.6"

# ==============================================================================
x-enabled-server: &enabled-server
  stop_signal: SIGTERM
  healthcheck:
    test: [ "CMD", "health" ]
    interval: 30s
    timeout: 15s
    retries: 5
    start_period: 10s
  environment:
    SERVER_PASSWORD: "12345"
#  volumes:
#    - ./temp/data:/data
#    - ./temp/backups:/backups
#    - ./temp/logs:/logs
  ports:
    - 2456:2456/udp
    - 2457:2457/udp

x-disabled-server: &disabled-server
  command: noop

# ==============================================================================
services:

  dos2unix:
    container_name: "dos2unix_helper"
    image: "adaliszk/valheim-server:${ENV_TAG:-dos2unix}"
    build: images/dos2unix

  vanilla:
    container_name: "valheim_vanilla"
    image: "adaliszk/valheim-server:${VANILLA_TAG:-develop}"
    build: images/vanilla
    <<: *enabled-server
    command:
      - -name "Name with spaces - and - dashes"
    depends_on:
      - dos2unix

#  valheim-plus:
#    image: "adaliszk/valheim-server:${PLUS_TAG:-plus0.9}"
#    build: server/valheim-plus
#    <<: *active-server
#    depends_on:
#      - vanilla
