# ==============================================================================
version: "3.8"

# ==============================================================================
volumes:
  server-data: {}
  server-backups: {}
  server-status: {}
  server-logs: {}

# ==============================================================================
x-enabled-server: &enabled-server
  environment:
    LOG_LEVEL: "debug"
    SERVER_ADMINS: "76561198108936133"
  volumes:
    - server-data:/data
    - server-backups:/backups
    - server-status:/status
    - server-logs:/logs
  ports:
    - 2456:2456/udp
    - 2457:2457/udp

x-disabled-server: &disabled-server
  command: noop

# ==============================================================================
services:

  vanilla:
    container_name: "valheim_vanilla"
    image: "adaliszk/valheim-server:${VANILLA_TAG:-0.205.5}"
    build: images/vanilla
    command: -password "super!secret"
    <<: *enabled-server

#  bepinex:
#    container_name: "valheim_bepinex"
#    image: "adaliszk/valheim-server:${VANILLA_TAG:-bepinex}"
#    build: images/bepinex
#    <<: *disabled-server
#    depends_on:
#      - vanilla
#
#  plus:
#    container_name: "valheim_plus"
#    image: "adaliszk/valheim-server:${VANILLA_TAG:-plus}"
#    build: images/plus
#    <<: *disabled-server
#    depends_on:
#      - vanilla

  metrics-exporter:
    container_name: "metrics_exporter"
    image: "adaliszk/valheim-server-monitoring:${EXPORTER_TAG:-metrics}"
    build: images/metrics-exporter
#    command:
#      - --v 1
    volumes:
      - ./temp/logs:/logs:ro
    ports:
      - 3903:3903

#  docker-exporter:
#    container_name: "docker_exporter"
#    image: "prometheusnet/docker_exporter:latest"
#    volumes:
#      - //var/run/docker.sock:/var/run/docker.sock:ro
#    ports:
#      - 3417:9417

#  prometheus:
#    container_name: "prometheus"
##    image: "prom/prometheus:latest"
#    image: "adaliszk/valheim-server-monitoring:${PROMETHEUS_TAG:-prometheus}"
#    build: images/prometheus
#    links:
#      - metrics-exporter
#      - docker-exporter
#    volumes:
#      - ./temp/prometheus:/prometheus
#    ports:
#      - 3090:9090

#  grafana:
#    container_name: "grafana"
#    image: "grafana/grafana:latest"
#    depends_on:
#      - prometheus
#    volumes:
#      - ./temp/grafana:/var/lib/grafana
#    ports:
#      - 3000:3000
