# ==============================================================================
version: "3.6"

# ==============================================================================
x-enabled-server: &enabled-server
  stop_signal: SIGTERM
  healthcheck:
    test: [ "CMD", "health" ]
    interval: 30s
    timeout: 15s
    retries: 5
    start_period: 10s
  environment:
    SERVER_PASSWORD: "12345"
  volumes:
    - ./temp/data:/data
    - ./temp/backups:/backups
    - ./temp/logs:/logs
  ports:
    - 2456:2456/udp
    - 2457:2457/udp

x-disabled-server: &disabled-server
  command: noop

# ==============================================================================
services:

  dos2unix:
    container_name: "dos2unix_helper"
    image: "adaliszk/valheim-server:${ENV_TAG:-dos2unix}"
    build: images/dos2unix

  vanilla:
    container_name: "valheim_vanilla"
    image: "adaliszk/valheim-server:${VANILLA_TAG:-latest}"
    build: images/vanilla
    <<: *enabled-server
    command:
      - -name "Name with spaces - and - dashes"
    depends_on:
      - dos2unix

  metrics-exporter:
    container_name: "metrics_exporter"
    image: "adaliszk/valheim-server:${EXPORTER_TAG:-metrics}"
    build: images/metrics-exporter
#    command:
#      - --v 1
    volumes:
      - ./temp/logs:/logs:ro
    ports:
      - 3903:3903

  docker-exporter:
    container_name: "docker_exporter"
    image: "prometheusnet/docker_exporter:latest"
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 3417:9417

  prometheus:
    container_name: "prometheus"
#    image: "prom/prometheus:latest"
    image: "adaliszk/valheim-server:${PROMETHEUS_TAG:-prometheus]"
    build: images/prometheus
    links:
      - metrics-exporter
      - docker-exporter
#    volumes:
#      - ./docs/examples/docker-prometheus.yml:/etc/prometheus/docker-prometheus.yml
#      - ./temp/prometheus:/prometheus
    ports:
      - 3090:9090

  grafana:
    container_name: "grafana"
    image: "grafana/grafana:latest"
    depends_on:
      - prometheus
    volumes:
      - ./temp/grafana:/var/lib/grafana
    ports:
      - 3000:3000
