# ==============================================================================
version: "3.8"

volumes:
  installation: {}
  vendorfiles: {}
  configs: {}
  data: {}

# ==============================================================================
services:

  server:
    user: "1001:1001"
    userns_mode: "host"
    container_name: "valheim-server"
    image: "adaliszk/valheim-server:${SERVER_TAG:-develop}"
    build:
      dockerfile: Dockerfile
      target: secure-valheim-server-bepinex
      context: .
      args:
        #STEAMCMD_EXTRAS: "-beta public-test -betapassword yesimadebackups"
        APP_VERSION: "0.212.7"
        APP_BUILD: "10062081"
    environment:
      SERVER_PASSWORD: "12345"
      SERVER_ADMINS: "76561198108936133"
      #SERVER_WORLD: "Something#With#Special@Characters"
    volumes:
      #- installation:/server/valheim_server_Data:uid=1001,gid=1001
      #- vendorfiles:/.config/unity3d/IronGate:uid=1001,gid=1001
      - configs:/data/configs:uid=1001,gid=1001,ro # simulate ConfigMap readonly-ness
      - data:/data:uid=1001,gid=1001
      - ./temp/mods:/data/plugins:uid=1001,gid=1001
    tmpfs:
      - /tmp/valheim-server:uid=1001,gid=1001
      - /tmp/state:uid=1001,gid=1001
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"