# ==============================================================================
version: "3.6"

# ==============================================================================
x-enabled-server: &enabled-server
  stop_signal: SIGTERM
  healthcheck:
    test: [ "CMD", "health" ]
    interval: 30s
    timeout: 15s
    retries: 5
    start_period: 10s
  environment:
    SERVER_PASSWORD: "12345"
  volumes:
    - ./temp/data:/home/steam/data
    - ./temp/backups:/home/steam/backups
    - ./temp/logs:/tmp/valheim
  ports:
    - 2456:2456/udp
    - 2457:2457/udp

x-disabled-server: &disabled-server
  command: noop
  volumes:
    - valheim-data:/home/steam/data
    - valheim-backup:/home/steam/backups
    - valheim-logs:/tmp/valheim

# ==============================================================================
volumes:
  valheim-data: {}
  valheim-backup: {}
  valheim-logs: {}

# ==============================================================================
services:

  dos2unix:
    image: "adaliszk/valheim-server:${ENV_TAG:-dos2unix}"
    build: docker/dos2unix

  vanilla:
    image: "adaliszk/valheim-server:${VANILLA_TAG:-latest}"
    build: server/vanilla
    <<: *enabled-server
    depends_on:
      - dos2unix

#  valheim-plus:
#    image: "adaliszk/valheim-server:${PLUS_TAG:-plus0.9}"
#    build: server/valheim-plus
#    <<: *active-server
#    depends_on:
#      - vanilla
