version: "3.8"

volumes:
  shared-logs: {}

services:

  valheim:
    image: "adaliszk/valheim-server:latest"
    environment:
      SERVER_NAME: "My Valheim Server"
      SERVER_PASSWORD: "super!secret"
    volumes:
      - shared-logs:/logs
    ports:
      - 2456:2456/udp
      - 2457:2457/udp

  metrics-exporter:
    container_name: "metrics_exporter"
    image: "adaliszk/valheim-server-monitoring:metrics"
    volumes:
      - shared-logs:/logs:ro
    ports:
      - 3903:3903

  docker-exporter:
    container_name: "docker_exporter"
    image: "prometheusnet/docker_exporter:latest"
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 3417:9417

  prometheus:
    container_name: "prometheus"
    image: "adaliszk/valheim-server:prometheus"
    links:
      - metrics-exporter
      - docker-exporter
    ports:
      - 3090:9090
