version: "3.8"

volumes:
  config: {}

services:

  init-config:
    image: busybox
    volumes:
      - config:/config
    command: |
      cat << EOF > /config/valheim_plus.cfg
      [Server]
      enabled=true
      maxPlayers=32
      disableServerPassword=true
      EOF

  valheim:
    image: adaliszk/valheim-server:plus
    environment:
      SERVER_NAME: "My Valheim Server"
      SERVER_PASSWORD: "super!secret"
    depends_on:
      - init-config
    volumes:
      - config:/config
    ports:
      - 2456:2456/udp
      - 2457:2457/udp