{
 "title": "Valheim Server",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "server_name", "label": "Server Name", "query": "valheim_vanilla" }
  ]
 },
 "panels": [
  {
   "title": "Players",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "server_players_online", "legendFormat": "players" }
   ]
  },
  {
   "title": "Online",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "server_players_online" }
   ]
  },
  {
   "title": "Day",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "world_day" }
   ]
  },
  {
   "title": "World Size [Objects]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "k" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "loaded_objects/1000", "legendFormat": "Loaded Objects" }
   ]
  },
  {
   "title": "Events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "event_random_possible", "legendFormat": "possibility" },
    { "expr": "event_random", "legendFormat": "{{ name }}" },
    { "expr": "event_found_location", "legendFormat": "{{ location }}" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(increase(docker_container_cpu_used_total{name=~\"$server_name\"}[30s]) / increase(docker_container_cpu_capacity_total[30s])) > 0 or (increase(docker_container_cpu_used_total{name=~\"$server_name\"}[1m]) / increase(docker_container_cpu_capacity_total[1m])) > 0 or (increase(docker_container_cpu_used_total{name=~\"$server_name\"}[3m]) / increase(docker_container_cpu_capacity_total[3m])) > 0 or (increase(docker_container_cpu_used_total{name=~\"$server_name\"}[5m]) / increase(docker_container_cpu_capacity_total[5m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Saves & GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "world_save_duration_avg", "legendFormat": "save" },
    {
     "expr": "garbage_collection_duration_avg",
     "legendFormat": "gc"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "docker_container_memory_used_bytes{name=\"valheim_vanilla\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "world_size_bytes", "legendFormat": "/data/worlds/{{ name}}.db" },
    { "expr": "backups_size_total_bytes", "legendFormat": "/backups" },
    { "expr": "world_size_total_bytes", "legendFormat": "/data/worlds" }
   ]
  },
  {
   "title": "Network I/O (+transmit, -receive)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "(rate(docker_container_network_in_bytes{name=~\"$server_name\"}[1m]) * -8)",
     "legendFormat": "RECEIVE"
    },
    {
     "expr": "(rate(docker_container_network_out_bytes{name=~\"$server_name\"}[1m]) * 8)",
     "legendFormat": "TRANSMIT"
    }
   ]
  },
  {
   "title": "Disk I/O (+write, -read)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "-rate(docker_container_disk_read_bytes{name=~\"$server_name\"}[1m])",
     "legendFormat": "READ"
    },
    {
     "expr": "rate(docker_container_disk_write_bytes{name=~\"$server_name\"}[1m])",
     "legendFormat": "WRITE"
    }
   ]
  }
 ]
}