{{- define "server_selectorLabels" -}}
adaliszk.io/type: Game
adaliszk.io/game: Valheim
adaliszk.io/name: {{ .Values.server.codeName }}
{{- end }}

{{- define "server_labels" -}}
{{ include "server_selectorLabels" . }}
{{- with .Values.server.labels }}
{{- toYaml . }}
{{- end }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{- define "server_name" -}}
valheim-{{ .Values.server.codeName | lower }}-server
{{- end }}

{{- define "server_config_name" -}}
{{ .Values.server.codeName | lower | default "valheim" }}-server-configs
{{- end }}

{{- define "pvc_data_name" -}}
{{ .Values.server.codeName | lower | default "valheim" }}-{{ .Values.server.world | lower | default "default" }}-{{ .Values.data.storageClass | default "standard" }}
{{- end }}

{{- define "pvc_backups_name" -}}
{{ .Values.server.codeName | lower | default "valheim" }}-backups-{{ .Values.backups.storageClass | default "standard" }}
{{- end }}
