{{- define "server_selectorLabels" -}}
adaliszk.io/type: server
adaliszk.io/name: {{ .Values.server.name }}
adaliszk.io/game: valheim
{{- end }}

{{- define "metrics_selectorLabels" -}}
adaliszk.io/type: metrics
adaliszk.io/name: {{ .Values.server.name }}
adaliszk.io/game: valheim
{{- end }}

{{- define "shared_labels" -}}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{- define "server_labels" -}}
{{ include "server_selectorLabels" . }}
{{- with .Values.server.labels }}
{{- toYaml . }}
{{- end }}
{{ include "shared_labels" . }}
{{- end }}

{{- define "metrics_labels" -}}
{{ include "metrics_selectorLabels" . }}
{{- with .Values.metrics.labels }}
{{- toYaml . }}
{{- end }}
{{ include "shared_labels" . }}
{{- end }}

{{- define "app_name" -}}
{{ .Values.server.name | lower | default "valheim" }}
{{- end }}

{{- define "pvc_data_name" -}}
{{ .Values.server.name | lower | default "valheim" }}-{{ .Values.server.persistentData.storageClass | default "standard" }}-{{ .Values.server.world | default "dedicated" | b32enc }}
{{- end }}

{{- define "pvc_logs_name" -}}
{{ .Values.server.name | lower | default "valheim" }}-{{ .Values.server.persistentLogs.storageClass | default "standard" }}-logs
{{- end }}

{{- define "pvc_backups_name" -}}
{{ .Values.server.name | lower | default "valheim" }}-{{ .Values.server.persistentBackups.storageClass | default "standard" }}-backups
{{- end }}
