---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "server_name" . }}
  labels:
    {{- include "server_labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "server_selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "server_selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001

      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        -
          name: {{ include "server_name" . }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SERVER_NAME
              value: "{{ .Values.server.name }}"
            - name: SERVER_PASSWORD
              value: "{{ .Values.server.password }}"
            - name: SERVER_WORLD
              value: "{{ .Values.server.world }}"
            - name: SERVER_PUBLIC
              value: "{{ .Values.server.public }}"

          ports:
            -
              name: valheim
              containerPort: 2456
              protocol: UDP
            -
              name: msqp
              containerPort: 2457
              protocol: UDP

          volumeMounts:
            -
              name: server-configs
              mountPath: /configs
              readOnly: true
            -
              name: auto-backups
              mountPath: /backups
            -
              name: server-data
              mountPath: /data
            -
              name: server-logs
              mountPath: /logs

          terminationMessagePath: /logs/exit.log
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: true
        {{- if .Values.metricsExporter.enabled -}}
        -
          name: {{ include "server_name" . }}-metrics
          image: "{{ .Values.metricsExporter.image.name }}:{{ .Values.metricsExporter.image.tag | default "metrics" }}"
          imagePullPolicy: {{ .Values.metricsExporter.image.pullPolicy }}
          ports:
            -
              name: http
              containerPort: 3903
              protocol: TCP

          volumeMounts:
            -
              name: server-logs
              mountPath: /logs

          terminationMessagePath: /logs/exit.log
          securityContext:
            allowPrivilegeEscalation: true
        {{- end }}
      terminationGracePeriodSeconds: 60
      volumes:
        -
          name: server-configs
          configMap:
            name: {{ include "server_config_name" . }}
        -
          name: auto-backups
          persistentVolumeClaim:
            claimName: {{ include "pvc_backups_name" . }}
        -
          name: server-data
          persistentVolumeClaim:
            claimName: {{ include "pvc_data_name" . }}
        -
          name: server-logs
          emptyDir: {}
