apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valheim-server.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "valheim-server.annotations" . | indent 4 }}
  labels:
    {{- include "valheim-server.labels" . | indent 4 }}
type: Opaque
data:
  password: {{ .Values.server.password | b64enc }}
