apiVersion: v1
kind: Service
metadata:
  name: {{ include "valheim-server.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "valheim-server.annotations" . | indent 4 }}
    {{- toYaml .Values.service.annotations  | nindent 4 }}
  labels:
    {{- include "valheim-server.labels" . | indent 4 }}
spec:
  type: LoadBalancer
  selector:
    {{- include "valheim-server.selectorLabels" . | indent 4 }}
  ports:
    -
      name: valheim
      targetPort: {{ .Values.service.valheimPort }}
      port: 2456
      protocol: UDP
    -
      name: steam
      targetPort: {{ .Values.service.steamPort }}
      port: 2457
      protocol: UDP
    -
      name: steam-default
      targetPort: {{ .Values.service.steamPort }}
      port: 27015
      protocol: UDP