---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "server_name" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "server.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001

      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      initContainers:
        -
          name: "show-data"
          image: k8s.gcr.io/busybox
          command: [ "/bin/sh", "-c", "ls -la /data"]
          volumeMounts:
            - name: server-data
              mountPath: /data
        -
          name: "show-backups"
          image: k8s.gcr.io/busybox
          command: [ "/bin/sh", "-c", "ls -la /backups" ]
          volumeMounts:
            - name: server-data
              mountPath: /data
      containers:
        -
          name: {{ include "server_name" . }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SERVER_NAME
              value: "{{ .Values.server.name }}"
            - name: SERVER_PASSWORD
              value: "{{ .Values.server.password }}"
            - name: SERVER_WORLD
              value: "{{ .Values.server.world }}"
            - name: SERVER_PUBLIC
              value: "{{ .Values.server.public }}"
          ports:
            - name: valheim
              containerPort: 2456
              protocol: UDP
            - name: msqp
              containerPort: 2457
              protocol: UDP
          volumeMounts:
            -
              name: server-configs
              mountPath: /configs
              readOnly: true
            -
              name: server-backups
              mountPath: /backups
            -
              name: server-data
              mountPath: /data
            -
              name: server-logs
              mountPath: /logs

          terminationMessagePath: /logs/exit.log
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: true
      terminationGracePeriodSeconds: 60
      volumes:
        -
          name: server-configs
          configMap:
            name: {{ include "server_config_name" . }}
        -
          name: server-backups
          persistentVolumeClaim:
            claimName: {{ include "pvc_backups_name" . }}
        -
          name: server-data
          persistentVolumeClaim:
            claimName: {{ include "pvc_data_name" . }}
        -
          name: server-logs
          persistentVolumeClaim:
            claimName: {{ include "pvc_logs_name" . }}
