---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "server_name" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  externalTrafficPolicy: Cluster
  selector:
    {{- include "server.selectorLabels" . | nindent 4 }}
  ports:

    - port: 2456
      targetPort: 2456
      protocol: UDP
      name: valheim

    - port: 2457
      targetPort: 2457
      protocol: UDP
      name: msqp

    - port: 27015
      targetPort: 2457
      protocol: UDP
      name: msqp-default
