apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app_name" . }}-server
  labels:
    {{- include "server_labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "server_selectorLabels" . | nindent 6 }}

  affinity: {{ .Values.server.affinity }}

  replicas: 1

  minReadySeconds: 20
  progressDeadlineSeconds: 600

  revisionHistoryLimit: 10

  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate

  template:
    metadata:
      labels:
        {{- include "server_selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001

      {{- with .Values.server.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        -
          name: {{ include "app_name" . }}-server
          image: "{{ .Values.server.image.name }}:{{ .Values.server.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          env:
            -
              name: SERVER_NAME
              value: "{{ .Values.server.motd }}"
            -
              name: SERVER_PASSWORD
              value: "{{ .Values.server.password }}"
            -
              name: SERVER_WORLD
              value: "{{ .Values.server.world }}"
            -
              name: SERVER_PUBLIC
              value: "{{ .Values.server.public }}"

          ports:
            -
              name: valheim
              containerPort: 2456
              protocol: UDP
            -
              name: msqp
              containerPort: 2457
              protocol: UDP

          volumeMounts:
            -
              name: server-configs
              mountPath: /configs
              readOnly: true
            -
              name: server-backups
              mountPath: /backups
            -
              name: server-data
              mountPath: /data
            -
              name: server-logs
              mountPath: /logs

          terminationMessagePath: /logs/exit.log
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: true
      terminationGracePeriodSeconds: 60
      volumes:
        -
          name: server-configs
          configMap:
            name: {{ include "server_config_name" . }}
        -
          name: server-backups
          persistentVolumeClaim:
            claimName: {{ include "pvc_backups_name" . }}
        -
          name: server-data
          persistentVolumeClaim:
            claimName: {{ include "pvc_data_name" . }}
        -
          name: server-logs
          persistentVolumeClaim:
            claimName: {{ include "pvc_logs_name" . }}
