apiVersion: v1
kind: Service
metadata:
  name: {{ include "app_name" . }}-server
  labels:
    {{- include "server_labels" . | nindent 4 }}
    {{- with .Values.server.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.server.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "server_selectorLabels" . | nindent 4 }}
  ports:
    {{- range $key, $value := .Values.server.ports }}
    - name: {{ $key }}
{{ toYaml $value | indent 6 }}
    {{- end }}