---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pvc_map_name" . }}
spec:
  storageClassName: {{ .Values.map.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.map.storageSize | default "100M" }}