---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pvc_data_name" . }}
spec:
  storageClassName: {{ .Values.data.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.data.storageSize | default "100M" }}