---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "server_config_name" . }}
  labels:
    {{- include "server_labels" . | nindent 4 }}
data:
  {{- with .Values.server.admins }}
  "adminlist.txt": |
    {{ . | nindent 4 }}
  {{- end }}
  {{- with .Values.server.admins }}
  "permittedlist.txt": |
    {{ . | nindent 4 }}
  {{- end }}
  {{- with .Values.server.admins }}
  "bannedlist.txt": |
    {{ . | nindent 4 }}
  {{- end }}
