---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pvc_data_name" . }}
spec:
  storageClassName: {{ .Values.server.persistentData.storageClass }}
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.server.persistentData.storageSize | default "2G" }}