---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mods_config_name" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
data:
  "BepInEx.cfg": |
    [Caching]
    EnableAssemblyCache = true

    [Harmony.Logger]
    LogChannels = Warn, Error

    [Logging]
    UnityLogListening = true
    LogConsoleToUnityLog = false

    [Logging.Console]
    Enabled = false
    ShiftJisEncoding = false
    StandardOutType = Auto
    LogLevels = Fatal, Error, Warning, Message, Info

    [Logging.Disk]
    Enabled = true
    WriteUnityLog = false
    AppendLog = false
    LogLevels = Fatal, Error, Warning, Message, Info

    [Preloader]
    ApplyRuntimePatches = true
    HarmonyBackend = auto
    DumpAssemblies = false
    LoadDumpedAssemblies = false
    BreakBeforeLoadAssemblies = false

    [Preloader.Entrypoint]
    Assembly = UnityEngine.CoreModule.dll
    Type = Application
    Method = .cctor

  "valheim_plus.cfg": |
    [Server]
    enabled = {{ .Values.plus.server.enabled }}
    maxPlayers={{ .Values.plus.server.maxPlayers }}
    disableServerPassword={{ .Values.plus.server.disableServerPassword }}
    enforceMod={{ .Values.plus.server.enforceMod }}
    dataRate={{ .Values.plus.server.dataRate }}
    autoSaveInterval={{ .Values.plus.server.autoSaveInterval }}

    [Game]
    enabled = {{ .Values.plus.game.enabled }}
    gameDifficultyDamageScale = {{ .Values.plus.game.gameDifficultyDamageScale }}
    gameDifficultyHealthScale = {{ .Values.plus.game.gameDifficultyHealthScale }}
    extraPlayerCountNearby = {{ .Values.plus.game.extraPlayerCountNearby }}
    setFixedPlayerCountTo = {{ .Values.plus.game.setFixedPlayerCountTo }}
    difficultyScaleRange = {{ .Values.plus.game.difficultyScaleRange }}

    [Time]
    enabled = {{ .Values.plus.time.enabled }}
    totalDayTimeInSeconds = {{ .Values.plus.time.totalDayTimeInSeconds }}
    nightTimeSpeedMultiplier = {{ .Values.plus.time.nightTimeSpeedMultiplier }}

    [Map]
    enabled = {{ .Values.plus.map.enabled }}
    shareMapProgression = {{ .Values.plus.map.shareMapProgression }}
    exploreRadius = {{ .Values.plus.map.exploreRadius }}
    playerPositionPublicOnJoin = {{ .Values.plus.map.playerPositionPublicOnJoin }}
    preventPlayerFromTurningOffPublicPosition = {{ .Values.plus.map.preventPlayerFromTurningOffPublicPosition }}
    removeDeathPinOnTombstoneEmpty = {{ .Values.plus.map.removeDeathPinOnTombstoneEmpty }}

    [Player]
    enabled = {{ .Values.plus.player.enabled }}
    baseMaximumWeight = {{ .Values.plus.player.baseMaximumWeight }}
    baseMegingjordBuff = {{ .Values.plus.player.baseMegingjordBuff }}
    baseAutoPickUpRange = {{ .Values.plus.player.baseAutoPickUpRange }}
    disableCameraShake = {{ .Values.plus.player.disableCameraShake }}
    baseUnarmedDamage = {{ .Values.plus.player.baseUnarmedDamage }}

    [Stamina]
    enabled = {{ .Values.plus.stamina.enabled }}
    dodgeStaminaUsage = {{ .Values.plus.stamina.dodgeStaminaUsage }}
    encumberedStaminaDrain = {{ .Values.plus.stamina.encumberedStaminaDrain }}
    jumpStaminaDrain = {{ .Values.plus.stamina.jumpStaminaDrain }}
    runStaminaDrain = {{ .Values.plus.stamina.runStaminaDrain }}
    sneakStaminaDrain = {{ .Values.plus.stamina.sneakStaminaDrain }}
    staminaRegen = {{ .Values.plus.stamina.staminaRegen }}
    staminaRegenDelay = {{ .Values.plus.stamina.staminaRegenDelay }}
    swimStaminaDrain = {{ .Values.plus.stamina.swimStaminaDrain }}

    [StaminaUsage]
    enabled = {{ .Values.plus.staminaUsage.enabled }}
    axes = {{ .Values.plus.staminaUsage.axes }}
    bows = {{ .Values.plus.staminaUsage.bows }}
    clubs = {{ .Values.plus.staminaUsage.clubs }}
    knives = {{ .Values.plus.staminaUsage.knives }}
    pickaxes = {{ .Values.plus.staminaUsage.pickaxes }}
    polearms = {{ .Values.plus.staminaUsage.polearms }}
    spears = {{ .Values.plus.staminaUsage.spears }}
    swords = {{ .Values.plus.staminaUsage.swords }}
    unarmed = {{ .Values.plus.staminaUsage.unarmed }}
    hammer = {{ .Values.plus.staminaUsage.hammer }}
    hoe = {{ .Values.plus.staminaUsage.hoe }}

    [Experience]
    enabled = {{ .Values.plus.experience.enabled }}
    swords = {{ .Values.plus.experience.swords }}
    knives = {{ .Values.plus.experience.knives }}
    clubs = {{ .Values.plus.experience.clubs }}
    polearms = {{ .Values.plus.experience.polearms }}
    spears = {{ .Values.plus.experience.spears }}
    blocking = {{ .Values.plus.experience.blocking }}
    axes = {{ .Values.plus.experience.axes }}
    bows = {{ .Values.plus.experience.bows }}
    fireMagic = {{ .Values.plus.experience.fireMagic }}
    frostMagic = {{ .Values.plus.experience.frostMagic }}
    unarmed = {{ .Values.plus.experience.unarmed }}
    pickaxes = {{ .Values.plus.experience.pickaxes }}
    woodCutting = {{ .Values.plus.experience.woodCutting }}
    jump = {{ .Values.plus.experience.jump }}
    sneak = {{ .Values.plus.experience.sneak }}
    run = {{ .Values.plus.experience.run }}
    swim = {{ .Values.plus.experience.swim }}

    [Camera]
    enabled = {{ .Values.plus.camera.enabled }}
    cameraMaximumZoomDistance = {{ .Values.plus.camera.cameraMaximumZoomDistance }}
    cameraBoatMaximumZoomDistance = {{ .Values.plus.camera.cameraBoatMaximumZoomDistance }}
    cameraFOV = {{ .Values.plus.camera.cameraFOV }}

    [Hud]
    enabled = {{ .Values.plus.hud.enabled }}
    showRequiredItems = {{ .Values.plus.hud.showRequiredItems }}
    experienceGainedNotifications = {{ .Values.plus.hud.experienceGainedNotifications }}

    [Hotkeys]
    enabled = {{ .Values.plus.hotkeys.enabled }}
    rollForwards = "{{ .Values.plus.hotkeys.rollForwards }}"
    rollBackwards = "{{ .Values.plus.hotkeys.rollBackwards }}"

    [AdvancedBuildingMode]
    enabled = {{ .Values.plus.advancedBuilding.enabled }}
    enterAdvancedBuildingMode = "{{ .Values.plus.advancedBuilding.enterAdvancedBuildingMode }}"
    exitAdvancedBuildingMode = "{{ .Values.plus.advancedBuilding.exitAdvancedBuildingMode }}"

    [AdvancedEditingMode]
    enabled = {{ .Values.plus.advancedEditing.enabled }}
    enterAdvancedEditingMode = "{{ .Values.plus.advancedEditing.enterAdvancedEditingMode }}"
    resetAdvancedEditingMode = "{{ .Values.plus.advancedEditing.resetAdvancedEditingMode }}"
    abortAndExitAdvancedEditingMode = "{{ .Values.plus.advancedEditing.abortAndExitAdvancedEditingMode }}"
    confirmPlacementOfAdvancedEditingMode = "{{ .Values.plus.advancedEditing.confirmPlacementOfAdvancedEditingMode }}"

    [Building]
    enabled = {{ .Values.plus.building.enabled }}
    noInvalidPlacementRestriction = {{ .Values.plus.building.noInvalidPlacementRestriction }}
    noWeatherDamage = {{ .Values.plus.building.noWeatherDamage }}
    maximumPlacementDistance = {{ .Values.plus.building.maximumPlacementDistance }}

    [StructuralIntegrity]
    enabled = {{ .Values.plus.structuralIntegrity.enabled }}
    disableStructuralIntegrity = {{ .Values.plus.structuralIntegrity.disableStructuralIntegrity }}
    wood = {{ .Values.plus.structuralIntegrity.wood }}
    stone = {{ .Values.plus.structuralIntegrity.stone }}
    iron = {{ .Values.plus.structuralIntegrity.iron }}
    hardWood = {{ .Values.plus.structuralIntegrity.hardwood }}

    [Items]
    enabled = {{ .Values.plus.items.enabled }}
    noTeleportPrevention = {{ .Values.plus.items.noTeleportPrevention }}
    baseItemWeightReduction = {{ .Values.plus.items.baseItemWeightReduction }}
    itemStackMultiplier = {{ .Values.plus.items.itemStackMultiplier }}

    [Workbench]
    enabled = {{ .Values.plus.workbench.enabled }}
    workbenchRange = {{ .Values.plus.workbench.workbenchRange }}
    disableRoofCheck = {{ .Values.plus.workbench.disableRoofCheck }}

    [Wagon]
    enabled = {{ .Values.plus.wagon.enabled }}
    wagonBaseMass = {{ .Values.plus.wagon.wagonBaseMass }}
    wagonExtraMassFromItems = {{ .Values.plus.wagon.wagonExtraMassFromItems }}

    [Beehive]
    enabled = {{ .Values.plus.beehive.enabled }}
    honeyProductionSpeed = {{ .Values.plus.beehive.honeyProductionSpeed }}
    maximumHoneyPerBeehive = {{ .Values.plus.beehive.maximumHoneyPerBeehive }}

    [Fermenter]
    enabled = {{ .Values.plus.fermenter.enabled }}
    fermenterDuration = {{ .Values.plus.fermenter.fermenterDuration }}
    fermenterItemsProduced = {{ .Values.plus.fermenter.fermenterItemsProduced }}

    [Fireplace]
    enabled = {{ .Values.plus.fireplace.enabled }}
    onlyTorches = {{ .Values.plus.fireplace.onlyTorches }}

    [Food]
    enabled = {{ .Values.plus.food.enabled }}
    foodDurationMultiplier = {{ .Values.plus.food.foodDurationMultiplier }}

    [Furnace]
    enabled = {{ .Values.plus.furnace.enabled }}
    maximumOre = {{ .Values.plus.furnace.maximumOre }}
    maximumCoal = {{ .Values.plus.furnace.maximumCoal }}
    coalUsedPerProduct = {{ .Values.plus.furnace.coalUsedPerProduct }}
    productionSpeed = {{ .Values.plus.furnace.productionSpeed }}

    [Kiln]
    enabled = {{ .Values.plus.kiln.enabled }}
    maximumWood = {{ .Values.plus.kiln.maximumWood }}
    productionSpeed = {{ .Values.plus.kiln.productionSpeed }}

    [Ward]
    enabled = {{ .Values.plus.ward.enabled }}
    wardRange = {{ .Values.plus.ward.wardRange }}