---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "server_config_name" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
data:
  "adminlist.txt": |
    {{ .Values.server.adminlist | nindent 4 }}
  "permittedlist.txt": |
    {{ .Values.server.whitelist | nindent 4 }}
  "bannedlist.txt": |
    {{ .Values.server.blacklist | nindent 4 }}
