global:
  # Default is every 1 minute.
  scrape_interval: 5s
  # The default is every 1 minute.
  evaluation_interval: 5s
  # The default is 10s.
  scrape_timeout: 3s

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:

  - job_name: 'valheim-server-metrics'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['metrics-exporter:3903']

  - job_name: 'container-metrics'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['container-exporter:9104']
