# =================================================================================================
name: "Helm"

# =================================================================================================
on:
  pull_request:
    paths:
      - .github/workflows/cd-helm.yml
      - chart/**/*
      - chart/*
    types:
      - synchronize
      - opened
  push:
    paths:
      - .github/workflows/cd-helm.yml
      - chart/**/*
      - chart/*
    branches:
      - develop
      - stable

# =================================================================================================
env:
  chart_repository: "https://charts.adaliszk.io"
  chart_deployment: "https://charts.adaliszk.io/chart/?name=valheim-server"
  chart_name: "adaliszk/valheim-server"
  chart_package: "valheim-server"

# =================================================================================================
jobs:

  #
  # STAGE: LINT
  #
  lint:
    runs-on: ubuntu-latest
    name: "Lint"
    steps:
      -
        name: "Checkout"
        uses: actions/checkout@v2
      -
        name: "Helm Lint"
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint ./chart

  #
  # STAGE: BUILD
  #
  bundle:
    needs: [ "lint" ]
    runs-on: ubuntu-latest
    name: "Bundle"
    steps:
      -
        name: "Checkout"
        uses: actions/checkout@v2
      -
        name: "Helm Package"
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm package ./chart
      -
        name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          path: "${{ env.chart_package }}-*"
          name: "${{ env.chart_package }}"

  #
  # STAGE: PUSH
  #
  push:
    #if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/stable'
    needs: [ "bundle" ]
    runs-on: ubuntu-latest
    name: "Push"
    steps:
      -
        name: "Download Artifact"
        uses: actions/download-artifact@v2
        with:
          name: "${{ env.chart_package }}"
      -
        id: deployment_info
        name: "Deploy to ${{ env.chart_repository }}"
        uses: chrnorm/deployment-action@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: "${{ env.chart_deployment }}"
          environment: charts.adaliszk.io
      -
        id: deployment
        name: "Upload to Chartmuseum"
        run: |
          PACKAGE=$(ls -1 ${{ env.chart_package }}-*)
          curl -u "${{ secrets.CHART_USERNAME }}:${{ secrets.CHART_PASSWORD }}" --data-binary "@${PACKAGE}" ${{ env.chart_repository }}/api/charts
      -
        if: always()
        name: "Update Deployment Status"
        uses: chrnorm/deployment-status@releases/v1
        with:
          deployment_id: ${{ steps.deployment_info.outputs.deployment_id }}
          token: "${{ github.token }}"
          target_url: "${{ env.chart_deployment }}"
          state: ${{ steps.deployment.outcome }}

