name: "Steam Update"
on:
  workflow_dispatch: {}
  push:
#    branches:
#      - develop
#      - stable
    paths:
      - .github/workflows/ci-steam-releases.yml
  schedule:
    # Check frequently before noon on workdays
    - cron: "*/5 8-12 * * 1-5"
    # Check semi-frequently after noon on workdays
    - cron: "*/15 12-18 * * 1-5"
    # Check infrequently by default
    - cron: "* 18-23 * * * "
    - cron: "* 0-8 * * * "


jobs:

  check-steam-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: steam-update
      -
        run: "echo \"::set-output name=has_update::$(bash .github/scripts/check-steam-update.sh)\""
      -
        uses: actions/upload-artifact@v2
        with:
          name: steam-update
          path: "steamapp-*"
          retention-days: 1

  trigger-workflows:
    if: ${{ jobs.check-steam-update.outputs.has_update }}
    needs: [ check-update ]
    runs-on: ubuntu-latest
    steps:
      - run: "echo \"Trigger other workflows that require a steam update\""
