name: "Steam Update"
on:
  workflow_dispatch: {}
  push:
#    branches:
#      - develop
#      - stable
    paths:
      - .github/workflows/ci-steam-releases.yml
  schedule:
    # Check frequently before noon on workdays
    - cron: "*/5 8-12 * * 1-5"
    # Check semi-frequently after noon on workdays
    - cron: "*/15 12-18 * * 1-5"
    # Check infrequently by default
    - cron: "* 18-23 * * * "
    - cron: "* 0-8 * * * "


env:
  cache_version: v1


jobs:

  check-steam-update:
    runs-on: ubuntu-latest
    outputs:
      has-update: ${{ steps.steam_update.outputs.has_update }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: steamapp-cache-${{ env.cache_version }}
          path: "steamapp-*"
      -
        run: |
          UPDATE_OUTPUT=$(bash .github/scripts/check-steam-update.sh)
          echo -e "check-steam-update(${?}):\n${UPDATE_OUTPUT:-(none-found)}"
          echo "::set-output name=has_update::${UPDATE_OUTPUT}"
        id: steam_update
      -
        uses: actions/upload-artifact@v2
        with:
          name: steamapp-cache-values
          path: "steamapp-*"
          retention-days: 1

  trigger-workflows:
    needs: [ check-steam-update ]
    if: ${{ needs.check-steam-update.outputs.has-update }}
    runs-on: ubuntu-latest
    steps:
      - run: "echo \"Trigger other workflows that require a steam update\""
