# =================================================================================================
name: "Docker Build"

# =================================================================================================
on:
  pull_request:
    types:
      - synchronize
      - opened
  push:
    branches:
      - develop
      - stable

# =================================================================================================
jobs:

  #
  # STAGE: LINT
  #
  lint:
    strategy:
      matrix:
        image: [ "dos2unix", "vanilla" ]
        include:
          - image: "dos2unix"
            path: "docker/dos2unix"
          - image: "vanilla"
            path: "server/vanilla"

    runs-on: ubuntu-latest
    name: "Lint"
    steps:

      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Shellcheck"
        uses: ludeeus/action-shellcheck@v1.0
        with:
          scandir: "./${{ matrix.path }}"

      - name: "Hadolint"
        uses: brpaz/hadolint-action@v1.2
        with:
          dockerfile: "${{ matrix.path }}/Dockerfile"

  #
  # STAGE: BUILD
  #
#  build-dos2unix:
#    needs: [ "lint" ]
#    runs-on: ubuntu-latest
